run:
    -mkdir -p pcm
    clang++ -std=c++20 -fmodules --precompile math.cppm -o pcm/math.pcm
    clang++ -std=c++20 -fmodules -c pcm/math.pcm -o math.o

    clang++ -std=c++20 -fmodules -fprebuilt-module-path=pcm --precompile geometry.cppm -o pcm/geometry.pcm
    clang++ -std=c++20 -fmodules -fprebuilt-module-path=pcm -c pcm/geometry.pcm -o geometry.o

    clang++ -std=c++20 -fmodules -fprebuilt-module-path=pcm main.cpp math.o geometry.o -o program

    ./program
